docker-build:
  # Use the official docker image.
  image: docker:stable
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add docker-compose
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - sudo docker build -t prominformatics .
    - echo "all right!"
  # Run this job in a branch where a Dockerfile exists

