docker-build:
  # Use the official docker image.
  image: python:3-slim
  stage: build
  services:
    - docker:dind
  before_script:
    - apt-get upgrade
    - apt install docker
    - docker login -u skytthepointofdark -p "13b8766d-d457-4779-8297-d240da6bfc28" 
    - apt install docker-compose
    - python3 -m pip install --upgrade pip
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - sleep 10
    - echo "all right!"
  # Run this job in a branch where a Dockerfile exists

