version: "3"

services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

  web:
    build: .
    ports:
      - "8080:8080"
    image: prominformatics
    volumes:
      - .:/prominf
    command: python3 manage.py runserver 0.0.0.0:8080
    restart: always
    depends_on:
      - db


