version: "2.1"

services:
  celery:
    image: celery:latest
    container_name: celery
    command: celery -A prominformatics worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/prominf
    build:
      context: ./
    depends_on:
      - celery-beat
  celery-beat:
    container_name: celery-beat
    command: celery -A prominformatics beat -l info
    build: .
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - .:/prominf
  db:
    restart: always
    container_name: db
    image: postgres:alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prominformatics_db
      - POSTGRES_USER=s104_prominformatics_user
      - POSTGRES_PASSWORD=s104_pr0m1nF0Rm4t1cs_Pa5S
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379

  web:
    healthcheck:
      test: curl -sS http://localhost:1337 || echo 1
      interval: 2s
      timeout: 20s
      retries: 3
    container_name: prominformatics_web
    build: .
    expose:
      - 8080
    image: prominformatics
    volumes:
      - .:/prominf
      - /var/run/docker.sock:/var/run/docker.sock
      - staticfiles:/prominf/staticfiles/
      - socket_files:/prominf/socketfiles/
    command: bash script.sh
    restart: always
    depends_on:
      - db
    links:
      - db:db

  nginx:
    container_name: prominformatics_nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - staticfiles:/prominf/staticfiles/
      - ./mediafiles/:/prominf/mediafiles/
      - run_config_0:/etc/cont_0/run_config
      - run_config_1:/etc/cont_1/run_config
      - run_config_2:/etc/cont_2/run_config
      - run_config_3:/etc/cont_3/run_config
      - run_config_4:/etc/cont_4/run_config


volumes:
  staticfiles:
  socket_files:
  redis:
  run_config_0:
  run_config_1:
  run_config_2:
  run_config_3:
  run_config_4: